settings:
  title: 'IRON Status Page'
  url: 'https://status.iron.security' # used for Slack messages
  logo: https://iron.security/img/favicon.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'Functional'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'Our platform infrastructure provider.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
 
  - id: crowdstrike-eu1
    name: eu-1.crowdstrike.com
    description: 'The EU instance of the Crowdstrike platform.'
    url: 'https://falcon.eu-1.crowdstrike.com/'
    method: GET
    expectSTatus: 200
    followRedirect: true
    linkable: false
    
  - id: iron-slack
    name: ironsecurity.slack.com
    description: 'Our Slack instance.'
    url: 'https://ironsecurity.slack.com/'
    method: GET
    expectSTatus: 200
    followRedirect: true
    linkable: false

  - id: iron-security
    name: iron.security
    description: 'IRON main public website'
    url: 'https://iron.security/'
    method: GET
    expectStatus: 200
    linkable: true
    
  - id: docs-iron-security
    name: docs.iron.security
    description: 'IRON documentation website'
    url: 'https://docs.iron.security/'
    method: GET
    expectStatus: 200
    linkable: true
    
  - id: app-iron-security
    name: app.iron.security
    description: 'IRON platform web interface'
    url: 'https://app.iron.security/'
    method: GET
    expectStatus: 200
    linkable: true
    
  - id: api-iron-security
    name: api.iron.security
    description: 'IRON platform API'
    url: 'https://api.iron.security/'
    method: GET
    expectStatus: 401
    linkable: true
