name = "cf-workers-status-page"
workers_dev = false
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2021-07-23"

[env.prd]
zone_id = '7e568a94bf4fe58607aec4b1677f80b1'
routes = ["status.iron.security"]

[triggers]
crons = ["*/2 * * * *"]

[site]
bucket = "out"
entry-point = "./"
